
package com.example.webclient.service.weather;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WeatherInterface", targetNamespace = "http://w.service.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WeatherInterface {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "WeatherInfo", targetNamespace = "")
    @RequestWrapper(localName = "findWeather", targetNamespace = "http://w.service.com", className = "com.service.weather.FindWeather")
    @ResponseWrapper(localName = "findWeatherResponse", targetNamespace = "http://w.service.com", className = "com.service.weather.FindWeatherResponse")
    @Action(input = "http://w.service.com/WeatherInterface/findWeatherRequest", output = "http://w.service.com/WeatherInterface/findWeatherResponse")
    public String findWeather(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
